#!/bin/bash
set -eux

curl -O -L https://github.com/hexagonrecursion/supercooling/releases/download/1.0/41fe1db9-74cf-4842-a8ea-f8e55281c9ad.nc
curl -O -L https://github.com/hexagonrecursion/supercooling/releases/download/1.0/a45203bd-8884-4178-a068-5d3e5c05e72e.nc
curl -O -L https://github.com/hexagonrecursion/supercooling/releases/download/1.0/d6867180-6444-4fd0-bda7-480197f76239.nc
